name: Run JAR

on:
  workflow_dispatch:   # Manuelles Starten im GitHub-UI möglich
  push:                # Optional: startet auch bei Push ins Repo

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run JAR file
        run: java -jar main.jar
